name: API CI/CD
on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/server.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Server Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ghcr.io/nglhrdt/scoreboard-server:latest
            ghcr.io/nglhrdt/scoreboard-server:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
